### ISSUE TITLE
¿Como puedo enviar un parametro a un middleware?

### ISSUE THREAD

**Issue by jorge-koki** [nicollassilva/minasrouter#1]
quiero enviar permisos por cada ruta, pero no veo la manera de enviar parámetros a cada ruta. Gracias por su gran trabajo

**Comment by nicollassilva** [comment]
Hi @jorge-koki , you can access the request inside the middleware, in the **handle** method. This method takes the request class and a next closure as parameters.

https://github.com/nicollassilva/minasrouter#request-route
